baseURL = 'http://stgoneira.github.io/prueba-hugo/'
languageCode = 'es-CL'
title = 'My Site using Hugo'
[[menu.main]]
  name = "Inicio"
  url = "/"  
  weight = 1
[[menu.main]]
  name = "Nosotros"
  url = "/nosotros"  
  weight = 2
[[menu.main]]
  name = "Contacto"
  url = "/contacto"
  weight = 3

